# Generated by Django 5.2 on 2025-05-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_document_user_document_profile_and_more"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="accounts.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("profile", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="user",
        ),
    ]
