# Generated by Django 5.2 on 2025-05-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0006_remove_document_user_document_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentguardian',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profiles', to='accounts.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='accounts.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
