# Generated by Django 5.2 on 2025-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_parentguardian_user_remove_staff_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teacher_subjects', to='academics.subject'),
        ),
    ]
