# Generated by Django 5.2 on 2025-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_alter_school_code_alter_school_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='SchoolSettings',
        ),
    ]
