# Generated by Django 5.2 on 2025-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_school_school_settings_delete_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='campus',
            name='country',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='state',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
