# Generated by Django 5.2 on 2025-05-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_school_country_remove_campus_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='school_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.school')),
            ],
        ),
    ]
