# Generated by Django 5.2 on 2025-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schooldocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
