# Generated by Django 5.2 on 2025-05-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campus_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone',
        ),
    ]
