# Generated by Django 5.2 on 2025-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_school_email_remove_school_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='category',
        ),
        migrations.RemoveField(
            model_name='school',
            name='code',
        ),
        migrations.RemoveField(
            model_name='school',
            name='country',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_type',
        ),
        migrations.AddField(
            model_name='campus',
            name='category',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('girls', 'Girls Only'), ('boys', 'Boys Only')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campus',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campus',
            name='school_type',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('kindergarten', 'Kindergarten'), ('university', 'University'), ('technical', 'Technical Institute')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
