# Generated by Django 5.2 on 2025-05-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_school_category_remove_school_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='director',
        ),
    ]
