# Generated by Django 5.2 on 2025-05-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_document_user_document_profile_and_more'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalincident',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='attended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_medical_visits', to='accounts.userprofile'),
        ),
    ]
