# Generated by Django 5.2 on 2025-04-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0002_campus_director_department_head_of_department_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.school')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('is_recurring', models.BooleanField(default=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.classroom')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_slots', to='academics.staff')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='timetable.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetable')),
            ],
            options={
                'ordering': ['day', 'time_slot__start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('specific_date__isnull', True)), fields=('timetable', 'day', 'time_slot', 'teacher'), name='unique_teacher_recurring_slot'), models.UniqueConstraint(condition=models.Q(('classroom__isnull', False), ('specific_date__isnull', True)), fields=('timetable', 'day', 'time_slot', 'classroom'), name='unique_classroom_recurring_slot'), models.UniqueConstraint(condition=models.Q(('specific_date__isnull', True)), fields=('timetable', 'day', 'time_slot', 'stream'), name='unique_stream_recurring_slot'), models.UniqueConstraint(condition=models.Q(('specific_date__isnull', False)), fields=('timetable', 'specific_date', 'time_slot', 'teacher'), name='unique_teacher_specific_slot'), models.UniqueConstraint(condition=models.Q(('classroom__isnull', False), ('specific_date__isnull', False)), fields=('timetable', 'specific_date', 'time_slot', 'classroom'), name='unique_classroom_specific_slot'), models.UniqueConstraint(condition=models.Q(('specific_date__isnull', False)), fields=('timetable', 'specific_date', 'time_slot', 'stream'), name='unique_stream_specific_slot')],
            },
        ),
    ]
