# Generated by Django 5.2 on 2025-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_document_user_document_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('school_owner', 'School Owner'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
