# Generated by Django 5.2 on 2025-05-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_permissioncategory_permission_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.permissioncategory'),
            preserve_default=False,
        ),
    ]
