# Generated by Django 5.2 on 2025-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='token_hash',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
