# Generated by Django 5.2 on 2025-05-02 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token_hash',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
