# Generated by Django 5.2 on 2025-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_emailverificationtoken_token_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='otp',
            field=models.CharField(default=1, editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
