# Generated by Django 5.2 on 2025-05-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_emailverificationtoken_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
    ]
