# Generated by Django 5.2 on 2025-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_emailverificationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('school_owner', 'School Owner'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], default='school_owner', max_length=20),
        ),
    ]
